name = "gleamrpc_http_server"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "HTTP server for GleamRPC"
licences = ["Apache-2.0"]
repository = { type = "github", user = "Billuc", repo = "gleamrpc_http_server" }
links = [
  { title = "Website", href = "https://hexdocs.pm/gleamrpc_http_server" },
  { title = "GleamRPC", href = "https://hexdocs.pm/gleamrpc" },
  { title = "HTTP client", href = "https://hexdocs.pm/gleamrpc_http_client" }  
]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.


internal_modules = [
  "gleamrpc_http_server",
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
mist = ">= 4.0.4 and < 5.0.0"
gleamrpc = ">= 2.1.0 and < 3.0.0"
convert = ">= 1.0.1 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
convert_http_query = ">= 1.0.0 and < 2.0.0"
convert_json = ">= 1.0.1 and < 2.0.0"
gleam_json = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
